/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gymManagement.view;


import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Dilanka Virajith
 */
public class Login extends javax.swing.JFrame {
    

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setTime();
        setDate();
        CapsLockLbl1.setVisible(false);
        boolean isOn = Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK);
        if (isOn == true) {
            CapsLockLbl1.setVisible(true);
        }
    }
    private void setTime() {
        new Thread(() -> {
            while (true) {
                Date date = new Date();
                String currentdate = new SimpleDateFormat("hh:mm:ss aa").format(date);
                
                TimeLbl.setText(currentdate);
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    
                }
            }
        }).start();
    }

    private void setDate() {
        Date now = new Date();
        SimpleDateFormat sf = new SimpleDateFormat("dd-MM-yyyy");
        DateLbl.setText(sf.format(now));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TimeLbl = new javax.swing.JLabel();
        DateLbl = new javax.swing.JLabel();
        LoginBtn = new javax.swing.JButton();
        UserNameTf = new javax.swing.JTextField();
        UserNameLbl = new javax.swing.JLabel();
        CapsLockLbl1 = new javax.swing.JLabel();
        PasswordPf = new javax.swing.JPasswordField();
        PasswordLbl = new javax.swing.JLabel();
        FrogetPasswordLbl1 = new javax.swing.JLabel();
        FrogetPasswordLbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        MinimizeLbl2 = new javax.swing.JLabel();
        zoomLbl2 = new javax.swing.JLabel();
        closeLbl2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TimeLbl.setFont(new java.awt.Font("Times New Roman", 0, 40)); // NOI18N
        TimeLbl.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(TimeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 90, 320, 60));

        DateLbl.setFont(new java.awt.Font("Times New Roman", 0, 40)); // NOI18N
        DateLbl.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(DateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 150, 320, 60));

        LoginBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        LoginBtn.setText("LOGIN");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });
        jPanel1.add(LoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 760, 310, 50));

        UserNameTf.setBackground(new java.awt.Color(51, 51, 51));
        UserNameTf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        UserNameTf.setForeground(new java.awt.Color(255, 255, 255));
        UserNameTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UserNameTfKeyPressed(evt);
            }
        });
        jPanel1.add(UserNameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 610, 40));

        UserNameLbl.setFont(new java.awt.Font("Neuropol X Rg", 1, 24)); // NOI18N
        UserNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        UserNameLbl.setText("User Name  :");
        jPanel1.add(UserNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 250, 40));

        CapsLockLbl1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        CapsLockLbl1.setForeground(new java.awt.Color(0, 153, 0));
        CapsLockLbl1.setText("Caps Lock Is On");
        jPanel1.add(CapsLockLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, 120, 30));

        PasswordPf.setBackground(new java.awt.Color(51, 51, 51));
        PasswordPf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        PasswordPf.setForeground(new java.awt.Color(255, 255, 255));
        PasswordPf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordPfKeyPressed(evt);
            }
        });
        jPanel1.add(PasswordPf, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 600, 620, 40));

        PasswordLbl.setFont(new java.awt.Font("Neuropol X Rg", 1, 24)); // NOI18N
        PasswordLbl.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLbl.setText("Password   :");
        jPanel1.add(PasswordLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 520, 250, 70));

        FrogetPasswordLbl1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        FrogetPasswordLbl1.setForeground(new java.awt.Color(0, 153, 0));
        FrogetPasswordLbl1.setText("Froget Your Password ?");
        jPanel1.add(FrogetPasswordLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 670, 160, 30));

        FrogetPasswordLbl.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        FrogetPasswordLbl.setForeground(new java.awt.Color(0, 153, 0));
        FrogetPasswordLbl.setText("Learn More");
        jPanel1.add(FrogetPasswordLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 670, 90, 30));

        jPanel3.setBackground(java.awt.Color.lightGray);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MinimizeLbl2.setBackground(java.awt.Color.lightGray);
        MinimizeLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MinimizeLbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gymManagement/images/minimize1.png"))); // NOI18N
        MinimizeLbl2.setOpaque(true);
        jPanel3.add(MinimizeLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1770, 0, 50, 30));

        zoomLbl2.setBackground(java.awt.Color.lightGray);
        zoomLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        zoomLbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gymManagement/images/zoooom.png"))); // NOI18N
        zoomLbl2.setOpaque(true);
        zoomLbl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                zoomLbl2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                zoomLbl2MouseExited(evt);
            }
        });
        jPanel3.add(zoomLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1820, 0, 50, 30));

        closeLbl2.setBackground(java.awt.Color.lightGray);
        closeLbl2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        closeLbl2.setForeground(new java.awt.Color(153, 153, 153));
        closeLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeLbl2.setText("X");
        closeLbl2.setOpaque(true);
        closeLbl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLbl2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeLbl2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeLbl2MouseExited(evt);
            }
        });
        jPanel3.add(closeLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1870, 0, 50, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gymManagement/images/Sports_Bodybuilding_Bodybuilding_Motivation_35033_1.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        String Username=UserNameTf.getText();
        String Password=PasswordPf.getText();
        if (Username.equals("dilanka")&&Password.equals("dilanka")) {
            new NewHomepage().setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Username or Password is incorrect");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void PasswordPfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordPfKeyPressed
        boolean isOn = Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK);
        if (isOn == true) {
            CapsLockLbl1.setVisible(true);
        } else {
            CapsLockLbl1.setVisible(false);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if ("".equals(PasswordPf.getText())) {
                JOptionPane.showMessageDialog(Login.this, "Please enter password");
            } else {
                LoginBtn.doClick();
            }

        }// TODO add your handling code here:
    }//GEN-LAST:event_PasswordPfKeyPressed

    private void UserNameTfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UserNameTfKeyPressed
        boolean isOn = Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK);
        if (isOn == true) {
            CapsLockLbl1.setVisible(true);
        } else {
            CapsLockLbl1.setVisible(false);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if ("".equals(UserNameTf.getText())) {
                JOptionPane.showMessageDialog(Login.this, "Please enter username");
            } else {
                PasswordPf.requestFocus();
            }

        }// TODO add your handling code here:
    }//GEN-LAST:event_UserNameTfKeyPressed

    private void zoomLbl2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zoomLbl2MouseEntered
        zoomLbl2.setBackground(Color.GRAY); // TODO add your handling code here:
    }//GEN-LAST:event_zoomLbl2MouseEntered

    private void zoomLbl2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zoomLbl2MouseExited
        zoomLbl2.setBackground(Color.lightGray);// TODO add your handling code here:
    }//GEN-LAST:event_zoomLbl2MouseExited

    private void closeLbl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLbl2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_closeLbl2MouseClicked

    private void closeLbl2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLbl2MouseEntered
        closeLbl2.setBackground(Color.red);// TODO add your handling code here:
    }//GEN-LAST:event_closeLbl2MouseEntered

    private void closeLbl2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLbl2MouseExited
        closeLbl2.setBackground(Color.lightGray);// TODO add your handling code here:
    }//GEN-LAST:event_closeLbl2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CapsLockLbl1;
    private javax.swing.JLabel DateLbl;
    private javax.swing.JLabel FrogetPasswordLbl;
    private javax.swing.JLabel FrogetPasswordLbl1;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JLabel MinimizeLbl2;
    private javax.swing.JLabel PasswordLbl;
    private javax.swing.JPasswordField PasswordPf;
    private javax.swing.JLabel TimeLbl;
    private javax.swing.JLabel UserNameLbl;
    private javax.swing.JTextField UserNameTf;
    private javax.swing.JLabel closeLbl2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel zoomLbl2;
    // End of variables declaration//GEN-END:variables
}
