/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gymManagement.view;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;



/**
 *
 * @author Dilanka Virajith
 */
public class NewHomepage extends javax.swing.JFrame {
    
     
    /**
     * Creates new form NewHomepage
     */
    public NewHomepage() {
        initComponents();
        setTime();
        setDate();
    }
    private void setTime() {
        new Thread(() -> {
            while (true) {
                Date date = new Date();
                String currentdate = new SimpleDateFormat("hh:mm:ss aa").format(date);
                
                Time2.setText(currentdate);
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    
                }
            }
        }).start();
    }

    private void setDate() {
        Date now = new Date();
        SimpleDateFormat sf = new SimpleDateFormat("dd-MM-yyyy");
        Date2.setText(sf.format(now));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        DashbordLbl = new javax.swing.JLabel();
        MemberLbl = new javax.swing.JLabel();
        AttendenceLbl = new javax.swing.JLabel();
        ScheduleLbl = new javax.swing.JLabel();
        PaymentLbl = new javax.swing.JLabel();
        InstructorLbl = new javax.swing.JLabel();
        ReportLbl = new javax.swing.JLabel();
        SettingLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CenterPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        MinimizeLbl = new javax.swing.JLabel();
        zoomLbl = new javax.swing.JLabel();
        closeLbl = new javax.swing.JLabel();
        Date2 = new javax.swing.JLabel();
        Time2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DashbordLbl.setBackground(new java.awt.Color(51, 51, 51));
        DashbordLbl.setFont(new java.awt.Font("Neuropol X Rg", 1, 24)); // NOI18N
        DashbordLbl.setForeground(new java.awt.Color(255, 255, 255));
        DashbordLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DashbordLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gymManagement/images/Entypo_e788(0)_32.png"))); // NOI18N
        DashbordLbl.setText(" Dashboard     ");
        DashbordLbl.setOpaque(true);
        DashbordLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashbordLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DashbordLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DashbordLblMouseExited(evt);
            }
        });
        jPanel2.add(DashbordLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 320, 70));

        MemberLbl.setBackground(new java.awt.Color(51, 51, 51));
        MemberLbl.setFont(new java.awt.Font("Neuropol X Rg", 1, 24)); // NOI18N
        MemberLbl.setForeground(new java.awt.Color(255, 255, 255));
        MemberLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MemberLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gymManagement/images/memberIcon.png"))); // NOI18N
        MemberLbl.setText(" Member          ");
        MemberLbl.setOpaque(true);
        MemberLbl.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                MemberLblAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        MemberLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MemberLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MemberLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MemberLblMouseExited(evt);
            }
        });
        jPanel2.add(MemberLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 320, 70));

        AttendenceLbl.setBackground(new java.awt.Color(51, 51, 51));
        AttendenceLbl.setFont(new java.awt.Font("Neuropol X Rg", 1, 24)); // NOI18N
        AttendenceLbl.setForeground(new java.awt.Color(255, 255, 255));
        AttendenceLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AttendenceLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gymManagement/images/AttendenceIcon.png"))); // NOI18N
        AttendenceLbl.setText(" Attendence   ");
        AttendenceLbl.setOpaque(true);
        AttendenceLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AttendenceLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AttendenceLblMouseExited(evt);
            }
        });
        AttendenceLbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AttendenceLblKeyPressed(evt);
            }
        });
        jPanel2.add(AttendenceLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 320, 70));

        ScheduleLbl.setBackground(new java.awt.Color(51, 51, 51));
        ScheduleLbl.setFont(new java.awt.Font("Neuropol X Rg", 1, 24)); // NOI18N
        ScheduleLbl.setForeground(new java.awt.Color(255, 255, 255));
        ScheduleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ScheduleLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gymManagement/images/ScheduleIcon.png"))); // NOI18N
        ScheduleLbl.setText(" Schedule       ");
        ScheduleLbl.setOpaque(true);
        ScheduleLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ScheduleLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ScheduleLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ScheduleLblMouseExited(evt);
            }
        });
        jPanel2.add(ScheduleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 320, 70));

        PaymentLbl.setBackground(new java.awt.Color(51, 51, 51));
        PaymentLbl.setFont(new java.awt.Font("Neuropol X Rg", 1, 24)); // NOI18N
        PaymentLbl.setForeground(new java.awt.Color(255, 255, 255));
        PaymentLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PaymentLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gymManagement/images/Payment.png"))); // NOI18N
        PaymentLbl.setText(" Payment        ");
        PaymentLbl.setOpaque(true);
        PaymentLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PaymentLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PaymentLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PaymentLblMouseExited(evt);
            }
        });
        jPanel2.add(PaymentLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 320, 70));

        InstructorLbl.setBackground(new java.awt.Color(51, 51, 51));
        InstructorLbl.setFont(new java.awt.Font("Neuropol X Rg", 1, 24)); // NOI18N
        InstructorLbl.setForeground(new java.awt.Color(255, 255, 255));
        InstructorLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InstructorLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gymManagement/images/instractorIcon.png"))); // NOI18N
        InstructorLbl.setText(" Instructors    ");
        InstructorLbl.setOpaque(true);
        InstructorLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InstructorLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InstructorLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InstructorLblMouseExited(evt);
            }
        });
        InstructorLbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                InstructorLblKeyPressed(evt);
            }
        });
        jPanel2.add(InstructorLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 320, 70));

        ReportLbl.setBackground(new java.awt.Color(51, 51, 51));
        ReportLbl.setFont(new java.awt.Font("Neuropol X Rg", 1, 24)); // NOI18N
        ReportLbl.setForeground(new java.awt.Color(255, 255, 255));
        ReportLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReportLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gymManagement/images/Reporticon.png"))); // NOI18N
        ReportLbl.setText(" Reports          ");
        ReportLbl.setOpaque(true);
        ReportLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ReportLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ReportLblMouseExited(evt);
            }
        });
        jPanel2.add(ReportLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 320, 70));

        SettingLbl.setBackground(new java.awt.Color(51, 51, 51));
        SettingLbl.setFont(new java.awt.Font("Neuropol X Rg", 1, 24)); // NOI18N
        SettingLbl.setForeground(new java.awt.Color(255, 255, 255));
        SettingLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SettingLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gymManagement/images/Settingicon.png"))); // NOI18N
        SettingLbl.setText(" Settings         ");
        SettingLbl.setOpaque(true);
        SettingLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SettingLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SettingLblMouseExited(evt);
            }
        });
        jPanel2.add(SettingLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 730, 320, 70));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gymManagement/images/Logout.png"))); // NOI18N
        jLabel1.setText("Logout");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 880, 140, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gymManagement/images/User.png"))); // NOI18N
        jLabel2.setText("User");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 880, 110, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 360, 940));

        CenterPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(5, 5, 5)));

        javax.swing.GroupLayout CenterPanelLayout = new javax.swing.GroupLayout(CenterPanel);
        CenterPanel.setLayout(CenterPanelLayout);
        CenterPanelLayout.setHorizontalGroup(
            CenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1528, Short.MAX_VALUE)
        );
        CenterPanelLayout.setVerticalGroup(
            CenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 938, Short.MAX_VALUE)
        );

        jPanel1.add(CenterPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 1530, 940));

        jPanel3.setBackground(java.awt.Color.lightGray);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MinimizeLbl.setBackground(java.awt.Color.lightGray);
        MinimizeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MinimizeLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gymManagement/images/minimize1.png"))); // NOI18N
        MinimizeLbl.setOpaque(true);
        jPanel3.add(MinimizeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1770, 0, 50, 30));

        zoomLbl.setBackground(java.awt.Color.lightGray);
        zoomLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        zoomLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gymManagement/images/zoooom.png"))); // NOI18N
        zoomLbl.setOpaque(true);
        zoomLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                zoomLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                zoomLblMouseExited(evt);
            }
        });
        jPanel3.add(zoomLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1820, 0, 50, 30));

        closeLbl.setBackground(java.awt.Color.lightGray);
        closeLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        closeLbl.setForeground(new java.awt.Color(153, 153, 153));
        closeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeLbl.setText("X");
        closeLbl.setOpaque(true);
        closeLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeLblMouseExited(evt);
            }
        });
        jPanel3.add(closeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1870, 0, 50, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 30));

        Date2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Date2.setForeground(new java.awt.Color(0, 204, 51));
        jPanel1.add(Date2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1750, 40, 160, 30));

        Time2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Time2.setForeground(new java.awt.Color(0, 204, 51));
        jPanel1.add(Time2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1750, 80, 160, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MemberLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MemberLblMouseClicked
        CenterPanel.removeAll();
        CenterPanel.setVisible(true);
        MemberRegistration co1 = new MemberRegistration();
        co1.setSize(CenterPanel.getSize());
        CenterPanel.add(co1);
        CenterPanel.repaint();
        CenterPanel.revalidate();
        co1.setVisible(true);
        
    }//GEN-LAST:event_MemberLblMouseClicked

    private void DashbordLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashbordLblMouseClicked
        CenterPanel.removeAll();
        CenterPanel.setVisible(true);
        CenterPanel.repaint();
        CenterPanel.revalidate();
        CenterPanel.setVisible(true);
    }//GEN-LAST:event_DashbordLblMouseClicked

    private void MemberLblAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_MemberLblAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_MemberLblAncestorAdded

    private void MemberLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MemberLblMouseEntered
        MemberLbl.setForeground(Color.green);
    }//GEN-LAST:event_MemberLblMouseEntered

    private void InstructorLblKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InstructorLblKeyPressed
       
    }//GEN-LAST:event_InstructorLblKeyPressed

    private void AttendenceLblKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AttendenceLblKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_AttendenceLblKeyPressed

    private void InstructorLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InstructorLblMouseClicked
        CenterPanel.removeAll();
        CenterPanel.setVisible(true);
        SubTrainerAdd sta = new SubTrainerAdd();
        sta.setSize(CenterPanel.getSize());
        CenterPanel.add(sta);
        CenterPanel.repaint();
        CenterPanel.revalidate();
        sta.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_InstructorLblMouseClicked

    private void closeLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLblMouseClicked
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_closeLblMouseClicked

    private void closeLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLblMouseEntered
        closeLbl.setBackground(Color.red);// TODO add your handling code here:
    }//GEN-LAST:event_closeLblMouseEntered

    private void closeLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLblMouseExited
        closeLbl.setBackground(Color.lightGray);// TODO add your handling code here:
    }//GEN-LAST:event_closeLblMouseExited

    private void zoomLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zoomLblMouseEntered
       zoomLbl.setBackground(Color.GRAY); // TODO add your handling code here:
    }//GEN-LAST:event_zoomLblMouseEntered

    private void zoomLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zoomLblMouseExited
        zoomLbl.setBackground(Color.lightGray);// TODO add your handling code here:
    }//GEN-LAST:event_zoomLblMouseExited

    private void ScheduleLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScheduleLblMouseClicked
        CenterPanel.removeAll();
        CenterPanel.setVisible(true);
        SubAddSchedule sas = new SubAddSchedule();
        sas.setSize(CenterPanel.getSize());
        CenterPanel.add(sas);
        CenterPanel.repaint();
        CenterPanel.revalidate();
        sas.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_ScheduleLblMouseClicked

    private void PaymentLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaymentLblMouseClicked
        CenterPanel.removeAll();
        CenterPanel.setVisible(true);
        SubPayment sp = new SubPayment();
        sp.setSize(CenterPanel.getSize());
        CenterPanel.add(sp);
        CenterPanel.repaint();
        CenterPanel.revalidate();
        sp.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_PaymentLblMouseClicked

    private void DashbordLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashbordLblMouseEntered
        DashbordLbl.setForeground(Color.green);
// TODO add your handling code here:
    }//GEN-LAST:event_DashbordLblMouseEntered

    private void DashbordLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashbordLblMouseExited
        DashbordLbl.setForeground(Color.white);
// TODO add your handling code here:
    }//GEN-LAST:event_DashbordLblMouseExited

    private void MemberLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MemberLblMouseExited
        MemberLbl.setForeground(Color.white);// TODO add your handling code here:
    }//GEN-LAST:event_MemberLblMouseExited

    private void AttendenceLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AttendenceLblMouseEntered
        AttendenceLbl.setForeground(Color.green);// TODO add your handling code here:
    }//GEN-LAST:event_AttendenceLblMouseEntered

    private void AttendenceLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AttendenceLblMouseExited
        AttendenceLbl.setForeground(Color.white);// TODO add your handling code here:
    }//GEN-LAST:event_AttendenceLblMouseExited

    private void ScheduleLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScheduleLblMouseEntered
        ScheduleLbl.setForeground(Color.green);// TODO add your handling code here:
    }//GEN-LAST:event_ScheduleLblMouseEntered

    private void ScheduleLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScheduleLblMouseExited
        ScheduleLbl.setForeground(Color.white);// TODO add your handling code here:
    }//GEN-LAST:event_ScheduleLblMouseExited

    private void PaymentLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaymentLblMouseEntered
        PaymentLbl.setForeground(Color.green);// TODO add your handling code here:
    }//GEN-LAST:event_PaymentLblMouseEntered

    private void PaymentLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaymentLblMouseExited
        PaymentLbl.setForeground(Color.white);// TODO add your handling code here:
    }//GEN-LAST:event_PaymentLblMouseExited

    private void InstructorLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InstructorLblMouseEntered
        InstructorLbl.setForeground(Color.green);// TODO add your handling code here:
    }//GEN-LAST:event_InstructorLblMouseEntered

    private void InstructorLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InstructorLblMouseExited
        InstructorLbl.setForeground(Color.white);// TODO add your handling code here:
    }//GEN-LAST:event_InstructorLblMouseExited

    private void ReportLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportLblMouseEntered
        ReportLbl.setForeground(Color.green);// TODO add your handling code here:
    }//GEN-LAST:event_ReportLblMouseEntered

    private void ReportLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportLblMouseExited
        ReportLbl.setForeground(Color.white);// TODO add your handling code here:
    }//GEN-LAST:event_ReportLblMouseExited

    private void SettingLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingLblMouseEntered
        SettingLbl.setForeground(Color.green);// TODO add your handling code here:
    }//GEN-LAST:event_SettingLblMouseEntered

    private void SettingLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingLblMouseExited
        SettingLbl.setForeground(Color.white);// TODO add your handling code here:
    }//GEN-LAST:event_SettingLblMouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        JOptionPane.showConfirmDialog(this,"Do you want to logout");
        int res=0;
        if (res == 0){
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewHomepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AttendenceLbl;
    private javax.swing.JPanel CenterPanel;
    private javax.swing.JLabel DashbordLbl;
    private javax.swing.JLabel Date2;
    private javax.swing.JLabel InstructorLbl;
    private javax.swing.JLabel MemberLbl;
    private javax.swing.JLabel MinimizeLbl;
    private javax.swing.JLabel PaymentLbl;
    private javax.swing.JLabel ReportLbl;
    private javax.swing.JLabel ScheduleLbl;
    private javax.swing.JLabel SettingLbl;
    private javax.swing.JLabel Time2;
    private javax.swing.JLabel closeLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel zoomLbl;
    // End of variables declaration//GEN-END:variables
}
