/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gymManagement.view;

import java.awt.Color;

/**
 *
 * @author Dilanka Virajith
 */
public class SubAddSchedule extends javax.swing.JPanel {

    /**
     * Creates new form SubAddSchedule
     */
    public SubAddSchedule() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchBtn = new javax.swing.JButton();
        AmountLbl = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        AmountStaLbl = new javax.swing.JLabel();
        DateTf = new javax.swing.JTextField();
        EndDateLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        CidLbl2 = new javax.swing.JLabel();
        SearchIdTf2 = new javax.swing.JTextField();
        CidLbl1 = new javax.swing.JLabel();
        SearchNameTf2 = new javax.swing.JTextField();
        BorderLbl1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        EndDateLbl1 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        AmountStaLbl1 = new javax.swing.JLabel();
        DateTf1 = new javax.swing.JTextField();
        AmountStaLbl2 = new javax.swing.JLabel();
        DateTf2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SearchBtn.setText("SEARCH");
        add(SearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 130, 30));

        AmountLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AmountLbl.setText("Name                :");
        add(AmountLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 160, 30));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 200, 30));

        AmountStaLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AmountStaLbl.setText("Schedule NO      :");
        add(AmountStaLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 160, 20));

        DateTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateTfActionPerformed(evt);
            }
        });
        add(DateTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 150, 310, 30));

        EndDateLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EndDateLbl.setText("Start Date          :");
        add(EndDateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 150, -1));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("Schedule information ");
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, 20));

        jLabel29.setBackground(new java.awt.Color(204, 204, 204));
        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 1240, 750));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 200, 30));

        jButton2.setText("PRINT SCHEDULE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 650, 150, 40));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Search by");
        jLabel3.setOpaque(true);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 90, 40));

        CidLbl2.setBackground(new java.awt.Color(0, 0, 0));
        CidLbl2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CidLbl2.setText("Membership NO : ");
        add(CidLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 40));
        add(SearchIdTf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 210, 30));

        CidLbl1.setBackground(new java.awt.Color(0, 0, 0));
        CidLbl1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CidLbl1.setText("Name              : ");
        add(CidLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 40));
        add(SearchNameTf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 210, 30));

        BorderLbl1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        add(BorderLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 260, 750));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Measurement Information");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, -1, 20));

        EndDateLbl1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EndDateLbl1.setText("End Date          :");
        add(EndDateLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 150, -1));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 200, 30));

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, 90, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, 70, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Neck");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, -1, -1));

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 90, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Chest");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, -1, -1));

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 90, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Abdomen");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, -1, -1));

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, 90, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Thight(L/R)");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 100, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Waist");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 580, 70, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Arm(L/R)");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 100, -1));

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 610, 90, 30));

        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 680, 90, 30));

        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 90, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("inch");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 410, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("inch");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("inch");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("inch");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("inch");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 620, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("kg");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 690, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("inch");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Weight");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 650, 70, -1));

        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 90, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("inch");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 480, -1, -1));

        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 470, 90, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("inch");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 480, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Forearm(L/R)");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, 120, -1));

        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 540, 90, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("inch");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 550, -1, -1));

        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 540, 90, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("inch");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 550, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("Calf(L/R)");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 580, 80, -1));

        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });
        add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 610, 90, 30));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("inch");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 620, -1, -1));

        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });
        add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 610, 90, 30));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("inch");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 620, -1, -1));

        jTextField21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField21ActionPerformed(evt);
            }
        });
        add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 750, 90, 30));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel27.setText("Height");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 720, 70, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("cm");
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 760, -1, -1));

        AmountStaLbl1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AmountStaLbl1.setText("Exercise  :");
        add(AmountStaLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 120, 160, 20));

        DateTf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateTf1ActionPerformed(evt);
            }
        });
        add(DateTf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 200, 30));

        AmountStaLbl2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AmountStaLbl2.setText("Set        :");
        add(AmountStaLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 200, 160, 20));

        DateTf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateTf2ActionPerformed(evt);
            }
        });
        add(DateTf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 230, 310, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Eid", "Exercise", "Set"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 280, 630, 400));

        jButton4.setText("REMOVE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 700, 150, 40));

        jButton5.setText("CONFIRM");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 840, 150, 40));

        jLabel30.setFont(new java.awt.Font("Neuropol X Rg", 1, 18)); // NOI18N
        jLabel30.setText("Manage Schedule");
        add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void DateTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateTfActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void jTextField21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField21ActionPerformed

    private void DateTf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateTf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateTf1ActionPerformed

    private void DateTf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateTf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateTf2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AmountLbl;
    private javax.swing.JLabel AmountStaLbl;
    private javax.swing.JLabel AmountStaLbl1;
    private javax.swing.JLabel AmountStaLbl2;
    private javax.swing.JLabel BorderLbl1;
    private javax.swing.JLabel CidLbl1;
    private javax.swing.JLabel CidLbl2;
    private javax.swing.JTextField DateTf;
    private javax.swing.JTextField DateTf1;
    private javax.swing.JTextField DateTf2;
    private javax.swing.JLabel EndDateLbl;
    private javax.swing.JLabel EndDateLbl1;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JTextField SearchIdTf2;
    private javax.swing.JTextField SearchNameTf2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
