/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gymManagement.view;

/**
 *
 * @author Dilanka Virajith
 */
public class SubPayment extends javax.swing.JPanel {

    /**
     * Creates new form SubPayment
     */
    public SubPayment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        CidLbl2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SearchIdTf2 = new javax.swing.JTextField();
        CidLbl1 = new javax.swing.JLabel();
        SearchNameTf2 = new javax.swing.JTextField();
        SearchBtn = new javax.swing.JButton();
        BorderLbl1 = new javax.swing.JLabel();
        CidLbl = new javax.swing.JLabel();
        CidTf = new javax.swing.JTextField();
        NicLbl = new javax.swing.JLabel();
        FNameLbl = new javax.swing.JLabel();
        FNameTf = new javax.swing.JTextField();
        LNameLbl = new javax.swing.JLabel();
        AgeTf = new javax.swing.JTextField();
        AgeLbl = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        CidTf1 = new javax.swing.JTextField();
        CidLbl3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Payments");
        jLabel2.setOpaque(true);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 90, 40));

        CidLbl2.setBackground(new java.awt.Color(0, 0, 0));
        CidLbl2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CidLbl2.setText("Membership NO : ");
        add(CidLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 40));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Search By");
        jLabel3.setOpaque(true);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 90, 40));
        add(SearchIdTf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 210, 30));

        CidLbl1.setBackground(new java.awt.Color(0, 0, 0));
        CidLbl1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CidLbl1.setText("NIC                 : ");
        add(CidLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, 40));
        add(SearchNameTf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 210, 30));

        SearchBtn.setText("SEARCH");
        add(SearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 130, 30));

        BorderLbl1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        add(BorderLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 270, 770));

        CidLbl.setBackground(new java.awt.Color(0, 0, 0));
        CidLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CidLbl.setText("Name               :");
        add(CidLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        CidTf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CidTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CidTfActionPerformed(evt);
            }
        });
        add(CidTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 440, 30));

        NicLbl.setBackground(new java.awt.Color(0, 0, 0));
        NicLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NicLbl.setText("Payment Type    :");
        add(NicLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 150, -1));

        FNameLbl.setBackground(new java.awt.Color(0, 0, 0));
        FNameLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        FNameLbl.setText("Amount            :");
        add(FNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 150, -1));

        FNameTf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FNameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNameTfActionPerformed(evt);
            }
        });
        add(FNameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 440, 30));

        LNameLbl.setBackground(new java.awt.Color(0, 0, 0));
        LNameLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LNameLbl.setText("Amount Status   :");
        add(LNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 160, 30));

        AgeTf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(AgeTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 550, 440, 30));

        AgeLbl.setBackground(new java.awt.Color(0, 0, 0));
        AgeLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AgeLbl.setText("Pending Amount :");
        add(AgeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 520, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 440, 30));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 440, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Amount", "Amount Status", "Pending Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, 710, 530));

        jButton5.setText("REMOVE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 680, 150, 40));

        jButton6.setText("PRINT BILL");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 850, 150, 40));

        CidTf1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CidTf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CidTf1ActionPerformed(evt);
            }
        });
        add(CidTf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 440, 30));

        CidLbl3.setBackground(new java.awt.Color(0, 0, 0));
        CidLbl3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CidLbl3.setText("Date                 :");
        add(CidLbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 1230, 770));

        jButton7.setText("UPDATE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 850, 150, 40));

        jButton8.setText("SAVE");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 850, 150, 40));

        jLabel30.setFont(new java.awt.Font("Neuropol X Rg", 1, 18)); // NOI18N
        jLabel30.setText("Manage Payments");
        add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void CidTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CidTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CidTfActionPerformed

    private void FNameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNameTfActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void CidTf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CidTf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CidTf1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeLbl;
    private javax.swing.JTextField AgeTf;
    private javax.swing.JLabel BorderLbl1;
    private javax.swing.JLabel CidLbl;
    private javax.swing.JLabel CidLbl1;
    private javax.swing.JLabel CidLbl2;
    private javax.swing.JLabel CidLbl3;
    private javax.swing.JTextField CidTf;
    private javax.swing.JTextField CidTf1;
    private javax.swing.JLabel FNameLbl;
    private javax.swing.JTextField FNameTf;
    private javax.swing.JLabel LNameLbl;
    private javax.swing.JLabel NicLbl;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JTextField SearchIdTf2;
    private javax.swing.JTextField SearchNameTf2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
