/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gymManagement.view;

import edu.ijse.gymManagement.controller.ClientController;
import edu.ijse.gymManagement.model.ClientDTO;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


    

/**
 *
 * @author Dilanka Virajith
 */
public class SubRegPayment extends javax.swing.JPanel {
    
     
    /**
     * Creates new form SubRegPayment
     */
    public SubRegPayment() {
        initComponents();
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BorderLbl1 = new javax.swing.JLabel();
        CidLbl2 = new javax.swing.JLabel();
        SearchIdTf2 = new javax.swing.JTextField();
        SearchNameTf2 = new javax.swing.JTextField();
        CidLbl1 = new javax.swing.JLabel();
        SearchBtn = new javax.swing.JButton();
        genderCombo = new javax.swing.JComboBox();
        LNameTf = new javax.swing.JTextField();
        GenderLbl = new javax.swing.JLabel();
        LNameLbl = new javax.swing.JLabel();
        FNameTf = new javax.swing.JTextField();
        FNameLbl = new javax.swing.JLabel();
        NicTf = new javax.swing.JTextField();
        NicLbl1 = new javax.swing.JLabel();
        MemberNoLbl = new javax.swing.JTextField();
        NicLbl = new javax.swing.JLabel();
        CidTf = new javax.swing.JTextField();
        CidLbl = new javax.swing.JLabel();
        AgeLbl = new javax.swing.JLabel();
        AgeTf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        AddressTa = new javax.swing.JTextArea();
        AddressLbl = new javax.swing.JLabel();
        EmailTf = new javax.swing.JTextField();
        EmailLbl = new javax.swing.JLabel();
        TelNoLbl = new javax.swing.JLabel();
        TelNoTf = new javax.swing.JTextField();
        NicLbl2 = new javax.swing.JLabel();
        DateLbl = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ClientTbl = new javax.swing.JTable();
        reloadBtn = new javax.swing.JButton();
        BorderLbl3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 700, 150, 40));

        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 700, 150, 40));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Search by");
        jLabel3.setOpaque(true);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 90, 40));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Personal Information");
        jLabel2.setOpaque(true);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 190, 40));

        BorderLbl1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        add(BorderLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 1230, 660));

        CidLbl2.setBackground(new java.awt.Color(0, 0, 0));
        CidLbl2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CidLbl2.setText("Client ID : ");
        add(CidLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 40));
        add(SearchIdTf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 210, 30));
        add(SearchNameTf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 210, 30));

        CidLbl1.setBackground(new java.awt.Color(0, 0, 0));
        CidLbl1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CidLbl1.setText("Name              : ");
        add(CidLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, 40));

        SearchBtn.setText("SEARCH");
        add(SearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 130, 30));

        genderCombo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        genderCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--", "Male", "Female" }));
        add(genderCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 440, 30));

        LNameTf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LNameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LNameTfActionPerformed(evt);
            }
        });
        add(LNameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 440, 30));

        GenderLbl.setBackground(new java.awt.Color(0, 0, 0));
        GenderLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        GenderLbl.setText("Gender           :");
        add(GenderLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, 30));

        LNameLbl.setBackground(new java.awt.Color(0, 0, 0));
        LNameLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LNameLbl.setText("Last Name       :");
        add(LNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, 30));

        FNameTf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FNameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNameTfActionPerformed(evt);
            }
        });
        add(FNameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 440, 30));

        FNameLbl.setBackground(new java.awt.Color(0, 0, 0));
        FNameLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        FNameLbl.setText("First Name       :");
        add(FNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 140, 30));

        NicTf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NicTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NicTfActionPerformed(evt);
            }
        });
        add(NicTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 440, 30));

        NicLbl1.setBackground(new java.awt.Color(0, 0, 0));
        NicLbl1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NicLbl1.setText("NIC                :");
        add(NicLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 140, 20));

        MemberNoLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MemberNoLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemberNoLblActionPerformed(evt);
            }
        });
        add(MemberNoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 440, 30));

        NicLbl.setBackground(new java.awt.Color(0, 0, 0));
        NicLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NicLbl.setText("Membership No:");
        add(NicLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 130, 30));

        CidTf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CidTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CidTfActionPerformed(evt);
            }
        });
        add(CidTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 440, 30));

        CidLbl.setBackground(new java.awt.Color(0, 0, 0));
        CidLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CidLbl.setText("Client ID         : ");
        add(CidLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, 40));

        AgeLbl.setBackground(new java.awt.Color(0, 0, 0));
        AgeLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AgeLbl.setText("Age              :");
        add(AgeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 110, -1, -1));

        AgeTf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AgeTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeTfActionPerformed(evt);
            }
        });
        add(AgeTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 110, 440, 30));

        AddressTa.setColumns(20);
        AddressTa.setRows(5);
        jScrollPane1.setViewportView(AddressTa);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 160, 440, 80));

        AddressLbl.setBackground(new java.awt.Color(0, 0, 0));
        AddressLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AddressLbl.setText("Address         :");
        add(AddressLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 160, -1, -1));

        EmailTf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(EmailTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 260, 440, 30));

        EmailLbl.setBackground(new java.awt.Color(0, 0, 0));
        EmailLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EmailLbl.setText("Email            :");
        add(EmailLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 260, -1, -1));

        TelNoLbl.setBackground(new java.awt.Color(0, 0, 0));
        TelNoLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TelNoLbl.setText("Tele No        :");
        add(TelNoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 310, -1, -1));

        TelNoTf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TelNoTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelNoTfActionPerformed(evt);
            }
        });
        add(TelNoTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 310, 440, 30));

        NicLbl2.setBackground(new java.awt.Color(0, 0, 0));
        NicLbl2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NicLbl2.setText("Date            :");
        add(NicLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 360, 120, 30));

        DateLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DateLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateLblActionPerformed(evt);
            }
        });
        add(DateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 360, 440, 30));

        ClientTbl.setBackground(new java.awt.Color(204, 204, 204));
        ClientTbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ClientTbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ClientTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Client ID", "Membership No", "NIC", "FirstName", "LastName", "Gender", "Age", "Address", "Email", "Tele No", "Date"
            }
        ));
        jScrollPane2.setViewportView(ClientTbl);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 1200, 280));

        reloadBtn.setText("RELOAD");
        reloadBtn.setBorder(null);
        reloadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadBtnActionPerformed(evt);
            }
        });
        add(reloadBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 700, 150, 40));

        BorderLbl3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        add(BorderLbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 230, 660));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void LNameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LNameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LNameTfActionPerformed

    private void FNameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNameTfActionPerformed

    private void NicTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NicTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NicTfActionPerformed

    private void MemberNoLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemberNoLblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MemberNoLblActionPerformed

    private void CidTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CidTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CidTfActionPerformed

    private void AgeTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeTfActionPerformed

    private void TelNoTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelNoTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelNoTfActionPerformed

    private void DateLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateLblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateLblActionPerformed

    private void reloadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadBtnActionPerformed
        try {
            ArrayList<ClientDTO> ClientList = ClientController.getAllClient();
            DefaultTableModel dtm = (DefaultTableModel) ClientTbl.getModel();
            dtm.setRowCount(0);
            for (ClientDTO c1 : ClientList) {
                Object[] rowData={c1.getClientID(),c1.getNIC(),c1.getFirstName(),c1.getLastName(),c1.getGender(),c1.getAge(),c1.getAddress(),c1.getEmail(),c1.getTelNo()};
                dtm.addRow(rowData);
            }
        } catch (Exception e) {
            System.out.println(e);
            e.printStackTrace();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_reloadBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLbl;
    private javax.swing.JTextArea AddressTa;
    private javax.swing.JLabel AgeLbl;
    private javax.swing.JTextField AgeTf;
    private javax.swing.JLabel BorderLbl1;
    private javax.swing.JLabel BorderLbl3;
    private javax.swing.JLabel CidLbl;
    private javax.swing.JLabel CidLbl1;
    private javax.swing.JLabel CidLbl2;
    private javax.swing.JTextField CidTf;
    private javax.swing.JTable ClientTbl;
    private javax.swing.JTextField DateLbl;
    private javax.swing.JLabel EmailLbl;
    private javax.swing.JTextField EmailTf;
    private javax.swing.JLabel FNameLbl;
    private javax.swing.JTextField FNameTf;
    private javax.swing.JLabel GenderLbl;
    private javax.swing.JLabel LNameLbl;
    private javax.swing.JTextField LNameTf;
    private javax.swing.JTextField MemberNoLbl;
    private javax.swing.JLabel NicLbl;
    private javax.swing.JLabel NicLbl1;
    private javax.swing.JLabel NicLbl2;
    private javax.swing.JTextField NicTf;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JTextField SearchIdTf2;
    private javax.swing.JTextField SearchNameTf2;
    private javax.swing.JLabel TelNoLbl;
    private javax.swing.JTextField TelNoTf;
    private javax.swing.JComboBox genderCombo;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton reloadBtn;
    // End of variables declaration//GEN-END:variables
}
