/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gymManagement.view;

import java.awt.Color;

/**
 *
 * @author Dilanka Virajith
 */
public class SubTrainerAdd extends javax.swing.JPanel {

    /**
     * Creates new form SubTrainerAdd
     */
    public SubTrainerAdd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CidLbl = new javax.swing.JLabel();
        IidTf = new javax.swing.JTextField();
        NicTf = new javax.swing.JTextField();
        NicLbl = new javax.swing.JLabel();
        FNameLbl = new javax.swing.JLabel();
        FNameTf = new javax.swing.JTextField();
        LNameLbl = new javax.swing.JLabel();
        LNameTf = new javax.swing.JTextField();
        AgeTf = new javax.swing.JTextField();
        AgeLbl = new javax.swing.JLabel();
        AddressLbl = new javax.swing.JLabel();
        EmailTf = new javax.swing.JTextField();
        EmailLbl = new javax.swing.JLabel();
        TelNoTf = new javax.swing.JTextField();
        TelNoLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        CidLbl1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        CidLbl2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CidLbl.setBackground(new java.awt.Color(0, 0, 0));
        CidLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CidLbl.setText("Instructor Id      :");
        add(CidLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        IidTf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IidTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IidTfActionPerformed(evt);
            }
        });
        add(IidTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 440, 30));

        NicTf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NicTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NicTfActionPerformed(evt);
            }
        });
        add(NicTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 440, 30));

        NicLbl.setBackground(new java.awt.Color(0, 0, 0));
        NicLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NicLbl.setText("NIC                 :");
        add(NicLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 150, -1));

        FNameLbl.setBackground(new java.awt.Color(0, 0, 0));
        FNameLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        FNameLbl.setText("First Name        :");
        add(FNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 150, -1));

        FNameTf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FNameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNameTfActionPerformed(evt);
            }
        });
        add(FNameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 440, 30));

        LNameLbl.setBackground(new java.awt.Color(0, 0, 0));
        LNameLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LNameLbl.setText("Last Name        :");
        add(LNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 160, 40));

        LNameTf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LNameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LNameTfActionPerformed(evt);
            }
        });
        add(LNameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 440, 30));

        AgeTf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(AgeTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 440, 30));

        AgeLbl.setBackground(new java.awt.Color(0, 0, 0));
        AgeLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AgeLbl.setText("Age                :");
        add(AgeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        AddressLbl.setBackground(new java.awt.Color(0, 0, 0));
        AddressLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AddressLbl.setText("Address           :");
        add(AddressLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        EmailTf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(EmailTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, 440, 30));

        EmailLbl.setBackground(new java.awt.Color(0, 0, 0));
        EmailLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EmailLbl.setText("Email               :");
        add(EmailLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, -1, -1));

        TelNoTf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TelNoTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelNoTfActionPerformed(evt);
            }
        });
        add(TelNoTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 600, 440, 30));

        TelNoLbl.setBackground(new java.awt.Color(0, 0, 0));
        TelNoLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TelNoLbl.setText("Tele No           :");
        add(TelNoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, -1, -1));

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Instructor ID", "NIC", "First Name", "Last Name", "Age", "Address", "Email", "Tele No"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, 800, 550));

        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1600, 640, 150, 40));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Personal Information");
        jLabel2.setOpaque(true);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 190, 40));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 670, 760));

        jButton3.setText("SEARCH");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 210, 150, 40));

        CidLbl1.setBackground(new java.awt.Color(0, 0, 0));
        CidLbl1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CidLbl1.setText("Instructor Id      :");
        add(CidLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 120, -1, -1));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Search by");
        jLabel3.setOpaque(true);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 100, 40));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 170, 170, -1));

        CidLbl2.setBackground(new java.awt.Color(0, 0, 0));
        CidLbl2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CidLbl2.setText("Name               :");
        add(CidLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 170, -1, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 120, 170, -1));

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, 820, 760));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 440, -1));

        jButton5.setText("CONFIRM");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 840, 150, 40));

        jButton6.setText("CONFIRM");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 840, 150, 40));

        jButton7.setText("CONFIRM");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 840, 150, 40));

        jLabel30.setFont(new java.awt.Font("Neuropol X Rg", 1, 18)); // NOI18N
        jLabel30.setText("Manage Instructors");
        add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void IidTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IidTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IidTfActionPerformed

    private void NicTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NicTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NicTfActionPerformed

    private void FNameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNameTfActionPerformed

    private void LNameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LNameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LNameTfActionPerformed

    private void TelNoTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelNoTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelNoTfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLbl;
    private javax.swing.JLabel AgeLbl;
    private javax.swing.JTextField AgeTf;
    private javax.swing.JLabel CidLbl;
    private javax.swing.JLabel CidLbl1;
    private javax.swing.JLabel CidLbl2;
    private javax.swing.JLabel EmailLbl;
    private javax.swing.JTextField EmailTf;
    private javax.swing.JLabel FNameLbl;
    private javax.swing.JTextField FNameTf;
    private javax.swing.JTextField IidTf;
    private javax.swing.JLabel LNameLbl;
    private javax.swing.JTextField LNameTf;
    private javax.swing.JLabel NicLbl;
    private javax.swing.JTextField NicTf;
    private javax.swing.JLabel TelNoLbl;
    private javax.swing.JTextField TelNoTf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
