/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.gymmanagement.view;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import lk.ijse.gymmanagement.controller.ControllerFactory;
import lk.ijse.gymmanagement.controller.custom.ExerciseController;
import lk.ijse.gymmanagement.dto.ExerciseDTO;

/**
 *
 * @author Dilanka Virajith
 */
public class ExersizePanel extends javax.swing.JPanel {

    /**
     * Creates new form ExersizePanel
     */
    private ExerciseController exerciseController;
    private DefaultTableModel dtm;
    private ExerciseController ctrlExercise;
    
    public ExersizePanel() {
        initComponents();
        exerciseController = (ExerciseController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.Exercise);
        dtm = (DefaultTableModel) ExerciseTbl.getModel();
        ctrlExercise = (ExerciseController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.Exercise);
        loadData();
    }
    private void loadData(){
        dtm.setRowCount(0);
        
        try {
            ArrayList<ExerciseDTO> allExerciseDTOs = ctrlExercise.getAll();
            
            if (allExerciseDTOs == null) {
                return;
            }
            for (ExerciseDTO exercise : allExerciseDTOs) {
                Object[] rowData = {
                    exercise.getId(),
                    exercise.getName(),
                };
                dtm.addRow(rowData);
                
            }
        } catch (Exception ex) {
            Logger.getLogger(ExersizePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CidLbl2 = new javax.swing.JLabel();
        ExerciseTf = new javax.swing.JTextField();
        CidLbl3 = new javax.swing.JLabel();
        EidTf = new javax.swing.JTextField();
        BtnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ExerciseTbl = new javax.swing.JTable();
        UpdateBtn = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 2));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CidLbl2.setBackground(new java.awt.Color(0, 0, 0));
        CidLbl2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CidLbl2.setText("Exersize            : ");
        add(CidLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 90, -1, 40));

        ExerciseTf.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(ExerciseTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 100, 330, 30));

        CidLbl3.setBackground(new java.awt.Color(0, 0, 0));
        CidLbl3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CidLbl3.setText("Ex ID               : ");
        add(CidLbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, 50));

        EidTf.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(EidTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 330, 30));

        BtnAdd.setText("ADD");
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });
        add(BtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 160, 150, 40));

        ExerciseTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Eid", "EName"
            }
        ));
        ExerciseTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExerciseTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ExerciseTbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 1090, 510));

        UpdateBtn.setText("UPDATE");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });
        add(UpdateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 830, 150, 40));

        jButton7.setText("REMOVE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 830, 150, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("Exersize information ");
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 20));

        jLabel29.setBackground(new java.awt.Color(204, 204, 204));
        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1490, 750));

        btnBack.setText("BACK");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 830, 150, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
        try {
            String eid = EidTf.getText();
            String ename = ExerciseTf.getText();
            
            ExerciseDTO exercise = new ExerciseDTO(eid, ename);
            boolean isAdded = exerciseController.add(exercise);
            if (isAdded) {
                JOptionPane.showMessageDialog(this, "adding sucses");
                loadData();
            }else{
                JOptionPane.showMessageDialog(this, "adding faild");
            }
        } catch (Exception ex) {
            Logger.getLogger(ExersizePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }//GEN-LAST:event_BtnAddActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        dtm.setRowCount(0);
        String id = EidTf.getText();
        String name = ExerciseTf.getText();
        
        ExerciseDTO exercise = new ExerciseDTO(id, name);
        
        try {
            boolean isUpdate = exerciseController.update(exercise);
            if (isUpdate) {
                dtm.setRowCount(0);
                
                ArrayList<ExerciseDTO> allExerciseDTOs = ctrlExercise.getAll();
                if (allExerciseDTOs == null) {
                    return;
                }
                for (ExerciseDTO exerciseDTO : allExerciseDTOs) {
                    Object[] rowData = {
                       exerciseDTO.getId(),
                       exerciseDTO.getName()
                    };
                    dtm.addRow(rowData);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(ExersizePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            String EID = dtm.getValueAt(ExerciseTbl.getSelectedRow(),0).toString();
            boolean deleted = ctrlExercise.delete(EID);
            if (deleted) {
                JOptionPane.showMessageDialog(this, "Remove succsus");
                
                int index = ExerciseTbl.getSelectedRow();
                dtm.removeRow(index);
            }else{
                JOptionPane.showMessageDialog(this, "Remove Faild");
            }
        } catch (Exception ex) {
            Logger.getLogger(ExersizePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked

    }//GEN-LAST:event_btnBackMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        NewHomepage frmHomePage = (NewHomepage) SwingUtilities.getWindowAncestor(this);
        frmHomePage.naviageToSettingsPanel();
    }//GEN-LAST:event_btnBackActionPerformed

    private void ExerciseTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExerciseTblMouseClicked
        
        EidTf.setText(ExerciseTbl.getValueAt(ExerciseTbl.getSelectedRow(),0).toString());
        ExerciseTf.setText(ExerciseTbl.getValueAt(ExerciseTbl.getSelectedRow(),1).toString());
    }//GEN-LAST:event_ExerciseTblMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JLabel CidLbl2;
    private javax.swing.JLabel CidLbl3;
    private javax.swing.JTextField EidTf;
    private javax.swing.JTable ExerciseTbl;
    private javax.swing.JTextField ExerciseTf;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
