/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.gymmanagement.view;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.gymmanagement.controller.ControllerFactory;
import lk.ijse.gymmanagement.controller.custom.ClientController;
import lk.ijse.gymmanagement.controller.custom.ExerciseController;
import lk.ijse.gymmanagement.controller.custom.InstructorController;
import lk.ijse.gymmanagement.controller.custom.RegistrationController;
import lk.ijse.gymmanagement.dto.ClientDTO;
import lk.ijse.gymmanagement.dto.ExerciseDTO;
import lk.ijse.gymmanagement.dto.InstructorDTO;
import lk.ijse.gymmanagement.dto.RegistrationDTO;

/**
 *
 * @author Dilanka Virajith
 */
public class SubAddSchedule extends javax.swing.JPanel {
    private ExerciseController ctrlexercise;
    private InstructorController ctrlinstructor;
    private ClientController ctrlclient;
    
    /**
     * Creates new form SubAddSchedule
     */
    public SubAddSchedule() {
        initComponents();
        classLoad();
        loadComboExercise();
        loadComboInstructor();
        loadCombomembershipNos();
        setDate();
        
    }
    
    public void classLoad(){
        ctrlexercise = (ExerciseController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.Exercise);
        ctrlinstructor =(InstructorController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.Instructor);
        ctrlclient = (ClientController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.Client);
    }
    private void loadComboExercise(){
        try {
            ArrayList<ExerciseDTO> all = ctrlexercise.getAll();
            ExerciseCombo.removeAllItems();
            for (ExerciseDTO all1 : all) {
                ExerciseCombo.addItem(all1.getName());
                
            }
        } catch (Exception ex) {
            Logger.getLogger(SubAddSchedule.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    private void loadComboInstructor(){
        try {
            ArrayList<InstructorDTO> all = ctrlinstructor.getAll(); 
            InstructorCombo.removeAllItems();
            for (InstructorDTO all2 : all) {
                InstructorCombo.addItem(all2.getInstructorID());
                
            }
   
        } catch (Exception ex) {
            Logger.getLogger(SubAddSchedule.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    private void loadCombomembershipNos(){
        try {
            ArrayList<ClientDTO> all = ctrlclient.getAll(); 
            MemberCombo.removeAllItems();
            for (ClientDTO all2 : all) {
                MemberCombo.addItem(all2.getClientID());
                
            }
        } catch (Exception ex) {
            Logger.getLogger(SubAddSchedule.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }
    private void setDate() {
        Date now = new Date();
        SimpleDateFormat sf = new SimpleDateFormat("dd-MM-yyyy");
        DateTf.setText(sf.format(now));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AmountLbl = new javax.swing.JLabel();
        NameTf = new javax.swing.JTextField();
        AmountStaLbl = new javax.swing.JLabel();
        EndDateLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        CidLbl2 = new javax.swing.JLabel();
        EndDateLbl1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AmountStaLbl1 = new javax.swing.JLabel();
        DateTf1 = new javax.swing.JTextField();
        AmountStaLbl2 = new javax.swing.JLabel();
        DateTf2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        ExerciseCombo = new javax.swing.JComboBox();
        jLabel32 = new javax.swing.JLabel();
        InstructorCombo = new javax.swing.JComboBox();
        jXDatePicker2 = new org.jdesktop.swingx.JXDatePicker();
        AmountStaLbl3 = new javax.swing.JLabel();
        instTf = new javax.swing.JTextField();
        MemberCombo = new javax.swing.JComboBox();
        DateTf = new javax.swing.JTextField();
        BorderLbl1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 2));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AmountLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AmountLbl.setText("Name                :");
        add(AmountLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 160, 30));

        NameTf.setEditable(false);
        NameTf.setBackground(new java.awt.Color(255, 255, 255));
        NameTf.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        NameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTfActionPerformed(evt);
            }
        });
        add(NameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 200, 30));

        AmountStaLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AmountStaLbl.setText("Schedule NO      :");
        add(AmountStaLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 160, 30));

        EndDateLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EndDateLbl.setText("Start Date          :");
        add(EndDateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 150, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("Schedule information ");
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, 20));

        jButton2.setText("PRINT SCHEDULE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 650, 150, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Search by");
        jLabel3.setOpaque(true);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, 40));

        jLabel29.setBackground(new java.awt.Color(204, 204, 204));
        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 1280, 760));

        CidLbl2.setBackground(new java.awt.Color(0, 0, 0));
        CidLbl2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CidLbl2.setText("Membership NO : ");
        add(CidLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 40));

        EndDateLbl1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EndDateLbl1.setText("End Date          :");
        add(EndDateLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 150, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, 70, -1));

        AmountStaLbl1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AmountStaLbl1.setText("Exercise      :");
        add(AmountStaLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, 160, 20));

        DateTf1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        DateTf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateTf1ActionPerformed(evt);
            }
        });
        add(DateTf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 200, 30));

        AmountStaLbl2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AmountStaLbl2.setText("Set                     :");
        add(AmountStaLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 230, 160, 20));

        DateTf2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        DateTf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateTf2ActionPerformed(evt);
            }
        });
        add(DateTf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 260, 310, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Schedule No", "Eid", "Instructor Name", "Exercise", "Set", "Start Date", "End Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 1250, 480));

        jButton4.setText("UPDATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 840, 150, 40));

        jButton5.setText("CONFIRM");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 840, 150, 40));

        jLabel30.setFont(new java.awt.Font("Neuropol X Rg", 1, 18)); // NOI18N
        jLabel30.setText("Manage Schedule");
        add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 20, -1, -1));

        ExerciseCombo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(ExerciseCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, 310, 30));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel32.setText("Instructor    :");
        add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, -1, 30));

        InstructorCombo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        InstructorCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                InstructorComboItemStateChanged(evt);
            }
        });
        add(InstructorCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 190, 310, 30));

        jXDatePicker2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(jXDatePicker2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 200, 30));

        AmountStaLbl3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AmountStaLbl3.setText("Instructer Name    :");
        add(AmountStaLbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 160, 200, 20));

        instTf.setEditable(false);
        instTf.setBackground(new java.awt.Color(255, 255, 255));
        instTf.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        instTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instTfActionPerformed(evt);
            }
        });
        add(instTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 190, 310, 30));

        MemberCombo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        MemberCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MemberComboItemStateChanged(evt);
            }
        });
        add(MemberCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 180, 30));

        DateTf.setEditable(false);
        DateTf.setBackground(new java.awt.Color(255, 255, 255));
        DateTf.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        DateTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateTfActionPerformed(evt);
            }
        });
        add(DateTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 200, 30));

        BorderLbl1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        add(BorderLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 210, 760));

        jButton1.setFont(new java.awt.Font("Neuropol X Rg", 1, 13)); // NOI18N
        jButton1.setText("Add New");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1209, 75, 240, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void NameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTfActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void DateTf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateTf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateTf1ActionPerformed

    private void DateTf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateTf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateTf2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void instTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_instTfActionPerformed

    private void InstructorComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_InstructorComboItemStateChanged
        String InstructorID = InstructorCombo.getSelectedItem().toString();
        
        try {
            InstructorDTO instructor = ctrlinstructor.search(InstructorID);
            if (instructor == null) {
                JOptionPane.showMessageDialog(this , "Instructor no found");
            }else{
                instTf.setText(instructor.getfName());
            }
        } catch (Exception ex) {
            Logger.getLogger(SubAddSchedule.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }//GEN-LAST:event_InstructorComboItemStateChanged

    private void MemberComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MemberComboItemStateChanged
        String ClientID = MemberCombo.getSelectedItem().toString();
        
        try {
            ClientDTO client = ctrlclient.search(ClientID);
            if (client == null) {
                JOptionPane.showMessageDialog(this , "client no found");
            }else{
                NameTf.setText(client.getfName());
            }
        } catch (Exception ex) {
            Logger.getLogger(SubAddSchedule.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MemberComboItemStateChanged

    private void DateTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateTfActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AmountLbl;
    private javax.swing.JLabel AmountStaLbl;
    private javax.swing.JLabel AmountStaLbl1;
    private javax.swing.JLabel AmountStaLbl2;
    private javax.swing.JLabel AmountStaLbl3;
    private javax.swing.JLabel BorderLbl1;
    private javax.swing.JLabel CidLbl2;
    private javax.swing.JTextField DateTf;
    private javax.swing.JTextField DateTf1;
    private javax.swing.JTextField DateTf2;
    private javax.swing.JLabel EndDateLbl;
    private javax.swing.JLabel EndDateLbl1;
    private javax.swing.JComboBox ExerciseCombo;
    private javax.swing.JComboBox InstructorCombo;
    private javax.swing.JComboBox MemberCombo;
    private javax.swing.JTextField NameTf;
    private javax.swing.JTextField instTf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker2;
    // End of variables declaration//GEN-END:variables

}
