/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.gymmanagement.view;

import com.sun.org.apache.xerces.internal.impl.dv.xs.DecimalDV;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import lk.ijse.gymmanagement.controller.ControllerFactory;
import lk.ijse.gymmanagement.controller.custom.ClientController;
import lk.ijse.gymmanagement.controller.custom.InstructorController;
import lk.ijse.gymmanagement.controller.custom.PaymentController;
import lk.ijse.gymmanagement.controller.custom.RegistrationController;
import lk.ijse.gymmanagement.dao.custom.impl.ClientDAOImpl;
import lk.ijse.gymmanagement.dto.ClientDTO;
import lk.ijse.gymmanagement.dto.PaymentDTO;
import lk.ijse.gymmanagement.dto.QueryPaymentDTO;
import lk.ijse.gymmanagement.dto.RegistrationDTO;
import lk.ijse.gymmanagement.idgenerator.IdGenerator;

/**
 *
 * @author Dilanka Virajith
 */
public class SubPayment extends javax.swing.JPanel {
    private ClientController ctrlClient;
    String type;
    private RegistrationController ctrlRegistration;
    private PaymentController paymentController;
    private PaymentController ctrlPayment;
    private DefaultTableModel dtmPayment;
    /**
     * Creates new form SubPayment
     */
    public SubPayment() {
        initComponents();
        setDate();
        //loadIds();
        //loadCombomembershipNo();
        dtmPayment = (DefaultTableModel) paymentTbl.getModel();
        ctrlPayment = (PaymentController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.Payment);
        ctrlClient = (ClientController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.Client);
        ctrlRegistration = (RegistrationController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.Registration);
        paymentController = (PaymentController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.Payment);
        loadMembershipNo();
        loadData();
    }
    private void setDate() {
        Date now = new Date();
        SimpleDateFormat sf = new SimpleDateFormat("dd-MM-yyyy");
        dateTxt.setText(sf.format(now));
    }
    private void loadMembershipNo(){
        try {
            ArrayList<RegistrationDTO> all = ctrlRegistration.getAll();
            comboMembership.removeAllItems();
            for(RegistrationDTO all2 : all){
                comboMembership.addItem(all2.getMembership_No());
            }
        } catch (Exception ex) {
            Logger.getLogger(AttendencePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    private void loadData(){
        try {
            dtmPayment.setRowCount(0);
            ArrayList<QueryPaymentDTO> queryPaymentDTOs = ctrlPayment.queryPaymentDTOs();
            
            for(QueryPaymentDTO queryPaymentDTO : queryPaymentDTOs){
                Object[] rowData = {
                    queryPaymentDTO.getMembership_No(),
                    queryPaymentDTO.getfName(),
                    queryPaymentDTO.getP_Date(),
                    queryPaymentDTO.getPID(),
                    queryPaymentDTO.getTypes(),
                    queryPaymentDTO.getAmount()
                    
                };
                dtmPayment.addRow(rowData);
            }
            
        } catch (Exception ex) {
            Logger.getLogger(SubPayment.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        CidLbl2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CidLbl = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        NicLbl = new javax.swing.JLabel();
        FNameLbl = new javax.swing.JLabel();
        amountTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        typeTxt = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        paymentTbl = new javax.swing.JTable();
        dateTxt = new javax.swing.JTextField();
        CidLbl3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        comboMembership = new javax.swing.JComboBox();
        BorderLbl1 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        CidLbl4 = new javax.swing.JLabel();
        pidTxt = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 2));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Payments");
        jLabel2.setOpaque(true);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 90, 40));

        CidLbl2.setBackground(new java.awt.Color(0, 0, 0));
        CidLbl2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CidLbl2.setText("Membership NO : ");
        add(CidLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Search By");
        jLabel3.setOpaque(true);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 90, 40));

        CidLbl.setBackground(new java.awt.Color(0, 0, 0));
        CidLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CidLbl.setText("Name               :");
        add(CidLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        txtName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 440, 30));

        NicLbl.setBackground(new java.awt.Color(0, 0, 0));
        NicLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NicLbl.setText("Payment Type    :");
        add(NicLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 150, -1));

        FNameLbl.setBackground(new java.awt.Color(0, 0, 0));
        FNameLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        FNameLbl.setText("Amount            :");
        add(FNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 150, -1));

        amountTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        amountTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTxtActionPerformed(evt);
            }
        });
        add(amountTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 440, 30));

        jButton1.setFont(new java.awt.Font("Neuropol X Rg", 1, 13)); // NOI18N
        jButton1.setText("New Payment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 80, 250, 40));

        typeTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        typeTxt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Monthly", "Registration", " " }));
        add(typeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 440, 30));

        paymentTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Membership No", "Name", "Date", "PID", "Payment Type", "Amount"
            }
        ));
        jScrollPane1.setViewportView(paymentTbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, 710, 530));

        dateTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        dateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTxtActionPerformed(evt);
            }
        });
        add(dateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 440, 30));

        CidLbl3.setBackground(new java.awt.Color(0, 0, 0));
        CidLbl3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CidLbl3.setText("Date                 :");
        add(CidLbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 1220, 750));

        comboMembership.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        comboMembership.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboMembershipItemStateChanged(evt);
            }
        });
        comboMembership.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMembershipActionPerformed(evt);
            }
        });
        add(comboMembership, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 190, 30));

        BorderLbl1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        add(BorderLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 270, 770));

        jButton8.setText("SAVE");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 830, 150, 40));

        jLabel30.setFont(new java.awt.Font("Neuropol X Rg", 1, 18)); // NOI18N
        jLabel30.setText("Manage Payments");
        add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 40, -1, -1));

        CidLbl4.setBackground(new java.awt.Color(0, 0, 0));
        CidLbl4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CidLbl4.setText("PID                  :");
        add(CidLbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));

        pidTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        pidTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pidTxtActionPerformed(evt);
            }
        });
        add(pidTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 440, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void amountTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountTxtActionPerformed

    private void dateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTxtActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        
        String mid = comboMembership.getSelectedItem().toString();
        
        String date = dateTxt.getText();
        String Pid = pidTxt.getText();
        if (typeTxt.getSelectedItem().equals("Monthly")){
            type = "Monthly";
        }
        if (typeTxt.getSelectedItem().equals("Registration")){
            type = "Registration";
        }else{
            
        }
        double newAmount = Double.parseDouble(amountTxt.getText());

        
        PaymentDTO payment = new PaymentDTO(Pid, date, type, newAmount, mid);
        try {
            boolean isAdd = paymentController.add(payment);
            if (isAdd) {
                JOptionPane.showMessageDialog(this, "Succsus");
                loadData();
            }else{
                JOptionPane.showMessageDialog(this, "Faild");
            }
        } catch (Exception ex) {
            Logger.getLogger(SubPayment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void pidTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pidTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pidTxtActionPerformed

    private void comboMembershipItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboMembershipItemStateChanged
        
    }//GEN-LAST:event_comboMembershipItemStateChanged

    private void comboMembershipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMembershipActionPerformed
        String Membership_No = comboMembership.getSelectedItem().toString();
        
        try {
            RegistrationDTO registration = ctrlRegistration.search(Membership_No);
            
                //NameTf.setText(registration.getMembership_No());
                ClientDTO client = ctrlClient.search(registration.getClientID());
                txtName.setText(client.getfName());
            
        } catch (Exception ex) {
            Logger.getLogger(AttendencePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboMembershipActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String id = IdGenerator.getNewAttendanceId("Payment", "PID", "P");
            pidTxt.setText(id);
            typeTxt.requestFocusInWindow();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SubPayment.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SubPayment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BorderLbl1;
    private javax.swing.JLabel CidLbl;
    private javax.swing.JLabel CidLbl2;
    private javax.swing.JLabel CidLbl3;
    private javax.swing.JLabel CidLbl4;
    private javax.swing.JLabel FNameLbl;
    private javax.swing.JLabel NicLbl;
    private javax.swing.JTextField amountTxt;
    private javax.swing.JComboBox comboMembership;
    private javax.swing.JTextField dateTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable paymentTbl;
    private javax.swing.JTextField pidTxt;
    private javax.swing.JTextField txtName;
    private javax.swing.JComboBox typeTxt;
    // End of variables declaration//GEN-END:variables

}
