/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.gymmanagement.view;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import lk.ijse.gymmanagement.controller.ControllerFactory;
import lk.ijse.gymmanagement.controller.custom.ClientController;
import lk.ijse.gymmanagement.dto.ClientDTO;


/**
 *
 * @author Dilanka Virajith
 */

public class ViewAllPanel extends javax.swing.JPanel {
    private ClientController ctrlClient;
    private DefaultTableModel dtmClient;
    /**
     * Creates new form ViewAllPanel
     */
    public ViewAllPanel() {
        initComponents();
        ctrlClient = (ClientController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.Client);
        dtmClient = (DefaultTableModel) ClientTbl2.getModel();
        loadData();
    }
    
    private void loadData() {
        dtmClient.setRowCount(0);
        try {
            ArrayList<ClientDTO> allClientDTOs = ctrlClient.getAll();

            if (allClientDTOs == null) {
                return;
            }
            for (ClientDTO client : allClientDTOs) {
                Object[] rowData = {
                    client.getClientID(),
                    client.getNic(),
                    client.getfName(),
                    client.getlName(),
                    client.getGender(),
                    client.getAge(),
                    client.getAddress(),
                    client.getEmail(),
                    client.getTelNo()
                };
                dtmClient.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageClients.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        ClientTbl2 = new javax.swing.JTable();
        jLabel30 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 2));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ClientTbl2.setBackground(new java.awt.Color(240, 240, 240));
        ClientTbl2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ClientTbl2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ClientTbl2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Client ID", "NIC", "FirstName", "LastName", "Gender", "Age", "Address", "Email", "Tele No"
            }
        ));
        ClientTbl2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ClientTbl2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        ClientTbl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClientTbl2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ClientTbl2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1500, 730));

        jLabel30.setFont(new java.awt.Font("Neuropol X Rg", 1, 18)); // NOI18N
        jLabel30.setText("View All Members");
        add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 50, -1, -1));

        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 830, 150, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        NewHomepage frmHomePage = (NewHomepage) SwingUtilities.getWindowAncestor(this);
        frmHomePage.naviageToDashBoard();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ClientTbl2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ClientTbl2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientTbl2AncestorAdded

    private void ClientTbl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientTbl2MouseClicked
        
    }//GEN-LAST:event_ClientTbl2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ClientTbl2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
